# Generated by Django 3.1.7 on 2021-03-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bronxmember',
            name='beer_outstanding',
            field=models.IntegerField(default=0),
        ),
    ]
